name: raglab
channels:
  - pytorch/label/nightly
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2023.12.12=h06a4308_0
  - cuda-cudart=11.8.89=0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=11.11.3.6=0
  - libfaiss=1.7.4=h5aaf3ed_206_cuda11.4.4_nightly
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - numpy=1.26.3=py39h5f9d8c6_0
  - numpy-base=1.26.3=py39hb5e798b_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=23.2=py39h06a4308_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.25.0
      - aiohttp==3.9.1
      - aioprometheus==23.12.0
      - aiosignal==1.3.1
      - alembic==1.13.1
      - anyio==4.2.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.14.0
      - backcall==0.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - bitarray==2.9.2
      - bitsandbytes==0.42.0
      - bleach==6.1.0
      - blinker==1.7.0
      - blis==0.7.11
      - bypy==1.8.4
      - cachetools==5.3.2
      - catalogue==2.0.10
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - colbert-ai==0.2.19
      - colorama==0.4.6
      - colorlog==6.8.2
      - comm==0.2.1
      - confection==0.1.4
      - cymem==2.0.8
      - dataclasses==0.6
      - dataclasses-json==0.6.4
      - datasets==2.14.7
      - debugpy==1.8.1
      - decorator==5.1.1
      - deepspeed==0.12.6
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dill==0.3.7
      - dirtyjson==1.0.8
      - distro==1.9.0
      - docopt==0.6.2
      - einops==0.7.0
      - evaluate==0.4.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - faiss-gpu==1.7.2
      - fastapi==0.109.0
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - flash-attn==2.2.0
      - flask==3.0.2
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - git-python==1.0.3
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-auth==2.26.2
      - google-auth-oauthlib==1.0.0
      - greenlet==3.0.3
      - grpcio==1.60.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.2
      - httptools==0.6.1
      - httpx==0.26.0
      - huggingface-hub==0.23.2
      - idna==3.6
      - importlib-metadata==7.0.1
      - ipykernel==6.29.2
      - ipython==8.12.3
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - json5==0.9.14
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.2
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - jupyterlab-widgets==3.0.10
      - langcodes==3.4.0
      - language-data==1.2.0
      - lxml==5.1.0
      - mako==1.3.2
      - marisa-trie==1.1.0
      - markdown==3.5.2
      - markupsafe==2.1.4
      - marshmallow==3.20.2
      - matplotlib-inline==0.1.6
      - mauve-text==0.3.0
      - mistune==3.0.2
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.15
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - nbclient==0.9.0
      - nbconvert==7.16.0
      - nbformat==5.9.2
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - notebook==7.1.0
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - onnx==1.15.0
      - openai==0.28.1
      - optuna==3.4.0
      - orjson==3.9.12
      - overrides==7.7.0
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.3
      - peft==0.7.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pipreqs==0.5.0
      - platformdirs==4.2.0
      - portalocker==2.8.2
      - preshed==3.0.9
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.2
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pudb==2024.1
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==1.10.13
      - pygments==2.17.2
      - pynvml==11.5.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - quantile-python==1.1
      - ranger-fm==1.9.3
      - ray==2.9.1
      - referencing==0.32.1
      - regex==2023.10.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rouge-score==0.1.2
      - rpds-py==0.17.1
      - rsa==4.9
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - ruff==0.1.15
      - sacrebleu==2.4.0
      - safetensors==0.4.2
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - send2trash==1.8.2
      - sentence-transformers==2.3.1
      - sentencepiece==0.1.99
      - six==1.16.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.25
      - srsly==2.4.8
      - stack-data==0.6.3
      - starlette==0.35.1
      - svgwrite==1.4.3
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.0
      - thinc==8.2.2
      - threadpoolctl==3.2.0
      - tiktoken==0.5.2
      - tinycss2==1.2.1
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torch==2.1.2
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.1
      - transformers==4.41.2
      - tree==0.2.4
      - triton==2.1.0
      - typer==0.9.0
      - types-python-dateutil==2.8.19.20240106
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - tzdata==2023.4
      - ujson==5.8.0
      - uri-template==1.3.0
      - urllib3==2.1.0
      - urwid==2.5.2
      - urwid-readline==0.13
      - uvicorn==0.27.0
      - uvloop==0.19.0
      - vllm==0.2.6
      - voyager==2.0.2
      - wasabi==1.1.2
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - weasel==0.3.4
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - websockets==12.0
      - werkzeug==3.0.1
      - wget==3.2
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
      - xformers==0.0.23.post1
      - xxhash==3.4.1
      - yarg==0.1.9
      - yarl==1.9.4
      - zipp==3.17.0
prefix: /workspace/miniconda3/envs/raglab-test_0603
